from .job_views import JobsListView, JobsDetailView
from .applicant_views import ApplyView, ListAppView, RetrieveDestroyAppView
from .employer_views import  EmployerJobListCreateView,EmployerApplicationListView,EmployerApplicationUpdateView
